### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-marpri-17#1]
Buen trabajo @marpri-17 !

Algunas pistas para acabarlo:

- [ ] Limpia e indenta el código.
- [ ] Activar el indentador en la evaluación final. Cuenta como un punto entero en la evaluación.
- [ ] Utiliza el nombre del Pokemon para el Alt de la imagen
- [ ] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by marpri-17** [comment]
Siento haber tardado! No había visto la notificación del issue, no volverá a pasar. Ya está resuelto, me ha costado pero con la ayuda de mis compis, que son las mejores, ya está arriba  :grinning:
